window.addEventListener("DOMContentLoaded", (ev)=>{
    /*grab the URL*/
    const URL=document.URL;
    
    /* check if it contains an ID, which means the user has clicked a movies view button */
    if(URL.includes("id=")){

        const strs = URL.split('?');
        const id = strs[1].replace("id=","");
        console.log(strs[0]);
        /* If an ID has been passed to the URL, Show the details modal window */
        document.querySelector("#DetailView").classList.remove("hidden");
        console.log(document.querySelector("div#outer-box>span.close"));

        /* This Event Listener is just to  give the X button functionality */
        document.querySelector("div#outer-box>span.close").addEventListener("click",(ev)=>{
            window.location.replace(strs[0]);
        });

        /*********************************************************
        * The rest of the code here is just to get the dynamic
        * 'Previous' and 'Next' navigation buttons working
        ********************************************************/

        /* Grab the list of videos that was generated by the php */
        const List = document.getElementsByClassName("Library")[0].children;

        /* Loop through the list till the movie with a matching ID is found */
        var current = '';   
        for(let Movie of List){
         
            /* once the Movie the user wants to view is found */
            if(Movie.children[2].children[0].href == URL){

                /* Check if Movie exists before the current movie*/          
                if(Movie.previousElementSibling!=null){

                    /* If there is, show the 'previous' button, and assign its href to that movie*/
                    document.querySelector("#PreviousMovie").classList.remove("hidden");  
                    document.getElementById("PreviousMovie").href = Movie.previousElementSibling.children[2].children[0].href;
                }else{
                    /* Otherwise, hide the 'previous' button */
                    document.querySelector("#PreviousMovie").classList.add("hidden");              
                }

                /* Repeat the same as above, but now checking for the next movie in the list */
                if(Movie.nextElementSibling!=null){
                    document.querySelector("#NextMovie").classList.remove("hidden");
                    document.getElementById("NextMovie").href = Movie.nextElementSibling.children[2].children[0].href;
                }else{
                    document.querySelector("#NextMovie").classList.add("hidden");              
                }
            }
        }
    }
});